#!/bin/bash 
function uptHostname() {
    read -p "Hostname: " newHost
    echo $newHost >> /etc/hostname
    cat /etc/hostname
}


function deployBase() {
    echo "Installing ${#basicReq[@]} Basic Requirements: ${basicReq[@]}"
    sleep 1
    for ea in "${basicReq[@]}"; do
        if command -v "$ea" &>/dev/null; then
            echo "$ea already installed, moving on!"
        else
            echo "Installing $ea"
            if sudo apt install "$ea" -y; then
                echo "$ea installed successfully"
            else
                echo "$ea was not installed successfully, check logs"
            fi
        fi
    done
}


# function toBeInstalled() {
#     echo "The following will be installed:"
#     echo ${toInstall[*]}
#     for ins in ${toInstall[*]}
#     do
#         sudo apt install $ins -y
#         echo ""
#         echo "$ins installed"
#         echo ""
#         sleep 1
#     done
# }


# sudo apt update 
# sudo apt upgrade -y
# toBeInstalled
# read -p "$(hostname) is the current hostname \ hit ENTER to continue" 
# sudo nano /etc/hostname
# bash /home/vnodesv/vNodesV_deploy/deploy/go_install.sh


# scp toBeInstall.sh vnodesv@10.0.0.3:/home/vnodesv && ssh -t vnodesv@10.0.0.3 sudo -S bash toBeInstall.sh 

# ssh -t ubuntu@cp.vnodes.cloud -p 11789 ssh -t vnodesv@10.0.0.3 -p 11265