#!/bin/bash 
function uptHostname() {
    read -p "Hostname: " newHost
    echo $newHost >> /etc/hostname
    cat /etc/hostname
}


function deployBase() {
    echo "Installing ${#basicReq[@]} Basic Requirements: ${basicReq[@]}"
    sleep 1
    sudo apt update && sudo apt upgrade -y 
    for ea in "${basicReq[@]}"; do
        if command -v "$ea" &>/dev/null; then
            echo "$ea already installed, moving on!"
        else
            echo "Installing $ea"
            if sudo apt install "$ea" -y; then
                echo "$ea installed successfully"
            else
                echo "$ea was not installed successfully, check logs"
            fi
        fi
    done
}


